plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.141'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

group = 'com.moepus'
version = '1.21.1-1.0.0'

neoForge {
    version = project.neoforge_version

    runs {
        client {
            client()
        }
        server {
            server()
        }
        data {
            data()
        }
    }

    mods {
        moestweaks {
            sourceSet sourceSets.main
        }
    }

    validateAccessTransformers = true
}

repositories {
    maven { url = 'https://mirrors.qlu.edu.cn/bmclapi' }
    maven { url = 'https://maven.neoforged.net/releases' }
}

dependencies {
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                'Specification-Title'   : 'MoesTweaks',
                'Specification-Vendor'  : 'Moepus',
                'Specification-Version' : '1',
                'Implementation-Title'  : project.name,
                'Implementation-Version': project.version,
                'Implementation-Vendor' : 'Moepus',
                'MixinConfigs'          : 'moestweaks.mixins.json'
        ] as LinkedHashMap, 'com.moepus.moestweaks')
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(Javadoc).configureEach {
    options.encoding = 'UTF-8'
}
